<h2 style="color:blue">Convert Celsius to Fahrenheit</h2><span style="color:blue">Write a program that reads a Celsius degree from the console and converts it to Fahrenheit and displays the result. The formula for the conversion is as follows:</span><br>

$$fahrenheit = \frac{9}{5} * celsius + 32$$
<span style="background:rgb(211,211,211)">Here is a sample run of the program:<br>
Enter a degree in Celsius: 43<br>
43 Celsius is 109.4 Fahrenheit</span>

In [2]:
#Obtain the input from the user 
celsiusValue = float(input("Enter a degree in Celsius: "))

#Convert to fahrenheit
fahrenheitValue = (9 / 5) * celsiusValue + 32

#Display the results 
print(celsiusValue, "Celsius is",fahrenheitValue,"Fahrenheit")

Enter a degree in Celsius: 43
43.0 Celsius is 109.4 Fahrenheit


<h2 style="color:blue; text-transform:uppercase">Compute the volume of a cylinder</h2><span style="color:blue">Write a program that reads in the radius and length of a cylinder and computes the area and volume using the following formulas:
$$area = radius * radius * pi$$
$$volume = area * length    $$
Here is a sample run:<br>
Enter the radius and length of a cylinder: 5.5, 12 <br>
The area is 95.0331 <br>
The volume is 1140.4 </span>

In [4]:
#Obtain the input from the user 
radiusCylinder, lengthCylinder = input("Enter the radius and length of a cylinder: ").split(",")

#Convert to float numbers
radiusCylinder = float(radiusCylinder)
lengthCylinder = float(lengthCylinder)

PI = 3.14159

#Compute the area
areaValue = radiusCylinder * radiusCylinder * PI

#Compute the volume
volumeValue = areaValue * PI

#Display the results 
print("The area is",format(areaValue, ".4f"))

#Display the results 
print("The volume is",format(volumeValue, ".1f"))

Enter the radius and length of a cylinder: 5.5,12
The area is 95.0331
The volume is 298.6


<h2 style="color:blue">Convert feet into meters</h2><span style="color:blue">Write a program that reads a number in feet, converts it to meters, and displays the result. One foot is 0.305 meters.<br>
Here is a sample run:<br>
Enter a value for feet:16.5<br>
16.5 feet is 5.0325 meters</span>

In [7]:
#Obtain the input from the user 
footValue = float(input("Enter a value for feet: "))

#Convert to meter
meterValue = footValue * 0.305

#Display the results 
print(footValue,"feet is",format(meterValue, ".4f"),"meters")

Enter a value for feet: 16.5
16.5 feet is 5.0325 meters


<h2 style="color:blue; text-transform:uppercase">Convert pounds into kilograms</h2><span style="color:blue">Write a program that converts pounds into kilograms. The program prompts the user to enter a value in pounds, converts it to kilograms, and displays the result. One pound is 0.454 Kilograms.</span><br>
<p style="color:blue">Here is a sample run:<br>
Enter a value for pounds:55.5<br>
55.5 feet is 25.197 Kilograms</p>

In [8]:
#Obtain the input from the user 
poundValue = float(input("Enter a value in pounds: "))

#Convert to meter
kilogramValue = poundValue * 0.454

#Display the results 
print(poundValue,"pounds is",format(kilogramValue, ".3f"),"kilograms")

Enter a value in pounds: 55.5
55.5 pounds is 25.197 kilograms


<h2>Financial Application: Calculate tips</h2> Write a program that reads the subtotal and the gratuity rate and compares the gratuity and total. For example, if the user enters 10 for the subtotal and 15% for the gratuity rate, the program displays 1.5 as the gratuity and 11.5 as the total.<br>
<p style="color:blue">Here is a sample run:<br>
Enter the subtotal and a gratuity rate: 55.5<br>
The gratuity is 2.35 and the total is 18.04</p>

In [10]:
#Obtain the input from the user 
subtotalValue, gratuityValue = input("Enter the subtotal and a gratuity rate: ").split(",")

#Convert to float Numbers
subtotalValue = float(subtotalValue)
gratuityValue = float(gratuityValue)

#Compute the gratuity and total
gratuity = (gratuityValue / 100) * subtotalValue
total = gratuity + subtotalValue

#Display the results 
print("The gratuity is",format(gratuity,".2f"), "and the total is", format(total, ".2f"))

Enter the subtotal and a gratuity rate: 15.69,15
The gratuity is 2.35 and the total is 18.04


<h2>Sum the digits in an integer</h2> Write a program that reads an integer between 0 and 1000 and adds all the digits in the integer. For example, if an integer is 932, the sum of all its digits is 14.<br>
<p style="color:blue">Here is a sample run:<br>
Enter a number between 0 and 1000:999<br>
The sum of the digits is 27</p>

In [14]:
#Obtain the input from the user 
inputValue = int(input("Enter a number between 0 and 1000: "))

#Extract the individual digits
lastDigit = inputValue % 10
remainingDigit = inputValue // 10
secondDigit = remainingDigit % 10
firstDigit = remainingDigit // 10

#Compute the sum of the number
totalSum = firstDigit + secondDigit + lastDigit

#Display the result
print("The sum of the digits is",totalSum)

Enter a number between 0 and 1000: 345
The sum of the digits is 12


<h2>Find the number of years and days</h2> Write a program that prompts the user to enter the minutes (e.g., 1 billion), and displays the number of years and days for the minutes. For simplicity, assume a year has 365 days.<br>
<p style="color:blue">Here is a sample run:<br>
Enter the number of minutes:1000000000<br>
1000000000 minutes is approximately 1902 years and 214 days</p>

In [20]:
#Obtain the input from the user 
minutesValue = int(input("Enter the number of minutes: "))

#Compute number of minutes in a year.. A year has 365 days
numberMinutesInYear = 365 * 24 * 60
numberMinutesInDay = 24 * 60

#Compute the number of year in minutes entered
numberOfYears = minutesValue // numberMinutesInYear
remainingMinutes = minutesValue % numberMinutesInYear
numberOfDays = remainingMinutes // numberMinutesInDay

print(minutesValue,"minutes is approximately",numberOfYears,"years and",numberOfDays,"days")

Enter the number of minutes: 1000000000
1000000000 minutes is approximately 1902 years and 214 days


<h2>Science:calculate energy</h2>Write a program that calculates the energy needed to heat water from an initial temperature to a final temperature. Your program should prompt the user to enter the amount of water in kilograms and the initial and final temperatures of the water. The formula to compute the energy is<br>
$$Q = M * (finalTemperature - initialTemperature) * 4184$$
where M is the weight of water in kilograms, temperatures are in degrees Celsius, and energy Q is measured in joules.<br>
<p style="color:blue">Here is a sample run:<br>
Enter the amount of water in kilograms: 55.5<br>
Enter the initial temperature: 3.5<br>
Enter the initial temperature: 10.5<br>
The energy needed is 1625484.0</p>

In [21]:
#Obtain the input from the user 
amountOfWater = float(input("Enter the amount of water in kilograms: "))
 
initialTemperature = float(input("Enter the initial temperature: "))

finalTemperature = float(input("Enter the final temperature: "))

#Compute the energy needed to heat the water using the formula provided
energyNeededValue = amountOfWater * (finalTemperature - initialTemperature) * 4184

#Display the results
print("The energy needed is",energyNeededValue)

Enter the amount of water in kilograms: 55.5
Enter the initial temperature: 3.5
Enter the final temperature: 10.5
The energy needed is 1625484.0


<h2>Science:wind-chill temperature</h2> How cold is it outside? The temperature alone is not enough to provide the answer. Other factors including wind speed, relative humidity, and sunshine play important roles in determining coldness outside. In 2001, the National Weather Service (NWS) implemented the new wind-chill temperature to measure the coldness using temperature and wind speed. The formula is given as follows: <br>
<span style="padding-left:15em">t<sub>wc</sub> = 35.74 + 0.6215t<sub>a</sub> - 35.75v<sup>0.16</sup> + 0.4275t<sub>a</sub>v<sup>0.16</sup></span> <br>
where t<sub>a</sub> is the outside temperature measured in degrees Fahrenheit and v is the speed measured in miles per hour. t<sub>wc</sub> is the wind-chill temperature. The formula cannot be used for wind speeds below 2mph or for temperatures below -58<sup>o</sup>F or above 41<sup>o</sup>F. Write a program that prompts the user to enter a temperature between -58<sup>o</sup>F and 41<sup>o</sup>F and a wind speed greater than or equal to 2 and displays the wind-chill temperature.
<p style="color:blue">Here is a sample run:<br>
Enter the temperature in Fahrenheit between -58 and 41: 5.3<br>
Enter the wind speed in miles per hour: 6<br>
The wind chill index is -5.56707</p>

In [24]:
#Obtain the input from the user 
temperature = float(input("Enter the temperature in Fahrenheit between -58 and 41: "))
 
windSpeed = float(input("Enter the wind speed in miles per hour: "))

#Compute the Wind Chill Index
windChillIndex = 35.74 + 0.6215*temperature  - 35.75*(windSpeed**0.16) + 0.4275*temperature*(windSpeed**0.16)

#Display the results
print("The wind chill index is",format(windChillIndex,".5f"))

Enter the temperature in Fahrenheit between -58 and 41: 5.3
Enter the wind speed in miles per hour: 6
The wind chill index is -5.56707


<h2>Physics: find runaway length</h2>Given an airplane's acceleration a and take-off speed v, you can compute the minimum runway length needed for an airplane to take off using the following formula: <br>

$$length = \frac{v^2 * 3}{2a} $$
Write a program that prompts the user to enter v in meters/second(m/s) and the acceleration a in meters/second squared(m/s<sup>2</sup>), and displays the minimum runway length.  
<p style="color:blue">Here is a sample run:<br>
Enter speed and acceleration:60, 3.5<br>
The minimum runway length for this airplane is 514.286 meters</p>

In [27]:
#Obtain the input from the user 
speedValue, accelerationValue = input("Enter speed and acceleration: ").split(",")

#Convert to float numbers
speedValue = float(speedValue)
accelerationValue = float(accelerationValue)

#Compute the minimum runway length
lengthValue = (speedValue ** 2) / (2 * accelerationValue)

#Display the results
print("The minimum runway length for this airplane is",format(lengthValue, ".3f"), "meters")

Enter speed and acceleration: 60,3.5
The minimum runway length for this airplane is 514.286 meters


<h2>Financial application: investment amount</h2> Suppose you want to deposit a certain amount of money into a savings account with a fixed annual interest rate. What amount do you need to deposit in order to have &dollar;5000 in the account after three years? The initial deposit amount can be obtained using the following formula: <br>

$$initialDepositAmount = \frac{finalAccountValue}{(1 + monthlyInterestRate)^n} $$
where <b>n</b> is the <b>number of months</b>.Write a program that prompts the user to enter final account value, annual interest rate in percent, and the number of years, and displays the initial deposit amount. <p style="color:blue">Here is a sample run:<br>
Enter final account value:1000 <br>
Enter annual interest rate in percent:4.25<br>
Enter number of years: 5<br>
Initial deposit value is 808.8639</p>

In [30]:
#Obtain the inputs from the user
finalAccountValue = float(input("Enter final account value: "))

annualInterestRate = float(input("Enter annual interest rate in percent: "))

numberOfYears = int(input("Enter number of years: "))

#Compute deposit amount
monthlyInterestRate = annualInterestRate / (12 * 100)

initialDepositAmount = finalAccountValue / (1 + monthlyInterestRate) ** (numberOfYears * 12)

print("Initial deposit value is",format(initialDepositAmount, ".4f"))

Enter final account value: 1000
Enter annual interest rate in percent: 4.25
Enter number of years: 5
Initial deposit value is 808.8639


<h2 style="color:blue">Geometry: area of a hexagon</h2><span style="color:blue">Write a program that prompts the user to enter the side of a hexagon and displays its area. The formula for computing the area of a hexagon is: <br> $$Area = \frac{3 * \sqrt{3} * s^2}{2} $$
where s is the length of a side.</span><span style="color:blue">Here is a sample run:<br>
Enter the side:5.5 <br>
The area of the hexagon is 78.59</span>

In [40]:
#Prompt the user for input
sideValue = float(input("Enter the side: "))

#Compute the area 
areaValue = (3 * (3 ** 0.5) * (sideValue ** 2)) / 2

print("The area of the hexagon is",format(areaValue, ".2f"))

Enter the side: 5.5
The area of the hexagon is 78.59


<h2>Health Application: compute BMI</h2> Body Mass index (BMI) is a measure of health based on weight. It can be calculated by taking your weight in kilograms and dividing it by the square of your height in meters. Write a program that prompts the user to enter a weight in pounds and height in inches and displays the BMI. Note that one pound is 0.45359237 kilograms and one inch is 0.0254 meters. <p style="color:blue">Here is a sample run:<br>
Enter weight in pounds: 95.5 <br>
Enter height in inches: 50 <br>
BMI is 26.8573</p>

In [43]:
#Prompt the user to enter the weight and height
weightInPounds = float(input("Enter weight in pounds: "))
heightInInches = float(input("Enter height in inches: "))

#Convert the weight and height to respective units
weightInKilograms = weightInPounds * 0.45359237
heightInMeters = heightInInches * 0.0254

#Compute the body mass index
bodyMassIndex = weightInKilograms / (heightInMeters ** 2)

print("BMI is", format(bodyMassIndex, ".4f"))

Enter weight in pounds: 95.5
Enter height in inches: 50
BMI is 26.8573


<h2>Financial Application: calculate future investment value</h2>Write a program that reads in an investment amount, the annual interest rate, and the number of years, and displays the future investment value using the following formula: <br>

$$futureInvestmentValue = investmentAmount * (1 + monthlyInterestRate)^n$$
where n is the number of months. For example, if you enter the amount 1000, an annual interest rate is 4.25%, and the number of years as 1, the future investment value is 1043.33. <p style="color:blue">Here is a sample run: <br>
Enter investment amount: 1000<br>
Enter annual interest rate: 4.25<br>
Enter number of years: 1<br>
Accumulated value is 1043.33

In [45]:
#Prompt the user for inputs
investmentAmount = float(input("Enter investment amount: "))

annualInterestRate = float(input("Enter annual interest rate: "))

numberOfYears = int(input("Enter the number of years: "))

#Compute the monthly interest rate and number of months 
monthlyInterestRate = annualInterestRate / (12 * 100)

numberOfMonths = numberOfYears * 12

#Compute the future investment value 
futureInvestmentValue = investmentAmount * ((1 + monthlyInterestRate) ** numberOfMonths)

print("Accumulated value is", format(futureInvestmentValue, ".4f"))

Enter investment amount: 1000
Enter annual interest rate: 4.25
Enter the number of years: 1
Accumulated value is 1043.3377


<h2>Financial Application: compound value</h2> Suppose you save &dollar;100 each month into a savings account with an annual interest rate of 5%. Therefore, the monthly interest rate is 0.05 / 12 0.00417. After the first month, the value in the account becomes:<br>
100 x (1 + 0.00417) = 100.417<br>
After the second month, the value in the account becomes<br> 
(100 + 100.417) x (1 + 0.00417) = 201.252<br>
After the third month, the value in the account becomes<br>
(100 + 201.252) x (1 + 0.00417) = 302.507<br>
and so on.Write a program that prompts the user to enter a monthly saving amount and displays the account value after the sixth month.<br> <p style="color:blue">Here is a simple run of the program: <br>
Enter the monthly saving amount: 100 <br>
After the sixth month, the account value is 608.81</p>

In [52]:
#Prompt the user to enter the monthly savings amount
savingsAmount = float(input("Enter the monthly saving amount: "))

INTEREST_MULTIPLIER = (1 + 0.00417)

#After first month
firstMonthValue = savingsAmount * INTEREST_MULTIPLIER

#After second month
secondMonthValue = (savingsAmount + firstMonthValue) * INTEREST_MULTIPLIER

#After third month
thirdMonthValue = (savingsAmount + secondMonthValue) * INTEREST_MULTIPLIER

#After fourth month
fourthMonthValue = (savingsAmount + thirdMonthValue) * INTEREST_MULTIPLIER

#After fifth month
fifthMonthValue = (savingsAmount + fourthMonthValue) * INTEREST_MULTIPLIER

#After sixth month
sixthMonthValue = (savingsAmount + fifthMonthValue) * INTEREST_MULTIPLIER

#Display the results
print("After the sixth month, the account value is",format(sixthMonthValue,".3f"))

Enter the monthly saving amount: 750
After the sixth month, the account value is 4566.136
